import { useEffect, useState } from "react";
import "./BuildingHubShared.css";
import forgeBg from "../../assets/game/card_forge_hub_bg.png";
import { canAfford, formatCost, useGameProgress, type ResourceCost } from "./Progress";
import { craftPower, hasPower, loadPowerState, toggleEquipPower, upgradePower, type PowerId } from "./PowerInventory";
interface Props{forgeLevel:number;memeEnergy:number;relics:number;bearFragments:number;onBack:()=>void;}
type Recipe={id:PowerId;icon:string;name:string;desc:string;cost:ResourceCost;level:number;charges:number;upgrade:ResourceCost};
const RECIPES:Recipe[]=[
{id:'frost',icon:'❄️',name:'Runa Mrozu',desc:'Aktywna karta mocy. Zamraża jeden cel na 1 turę.',cost:{memeEnergy:40,relics:1,intel:1},level:1,charges:3,upgrade:{memeEnergy:55,relics:1,cardFragments:1}},
{id:'guard',icon:'🛡️',name:'Pieczęć Strażnika',desc:'Tworzy tarczę dla Pepe albo Bociana. Wybierasz chronioną postać.',cost:{memeEnergy:55,relics:1,bearFragments:1},level:1,charges:3,upgrade:{memeEnergy:65,relics:2,cardFragments:1}},
{id:'sleep',icon:'💤',name:'Pył Snu',desc:'Usypia pojedynczego przeciwnika. Trafienie może go obudzić.',cost:{memeEnergy:65,relics:2,bearFragments:1,cardFragments:1},level:2,charges:2,upgrade:{memeEnergy:80,relics:2,cardFragments:2}},
{id:'storm',icon:'⚡',name:'Rdzeń Burzy',desc:'Łańcuchowy piorun w 2–3 cele. Karta ofensywna.',cost:{memeEnergy:90,relics:3,bearFragments:2,cardFragments:2},level:2,charges:2,upgrade:{memeEnergy:110,relics:3,cardFragments:3}},
{id:'renewal',icon:'✚',name:'Totem Odnowy',desc:'Awaryjne leczenie drużyny w trakcie walki.',cost:{memeEnergy:80,relics:2,comicFragments:1,cardFragments:2},level:3,charges:2,upgrade:{memeEnergy:100,relics:3,cardFragments:3}},
];
export default function CardForgeHub({onBack}:Props){const {progress,spendResources}=useGameProgress();const [powers,setPowers]=useState(loadPowerState);useEffect(()=>{const h=(e:Event)=>setPowers((e as CustomEvent).detail??loadPowerState());window.addEventListener('plpe-power-state-sync',h);return()=>window.removeEventListener('plpe-power-state-sync',h)},[]);const forge=progress.buildings.cardForge;
function make(r:Recipe){if(!canAfford(progress,r.cost)||!spendResources(r.cost))return;setPowers(craftPower(loadPowerState(),r.id,r.charges))}
function levelUp(r:Recipe){if(!canAfford(progress,r.upgrade)||!spendResources(r.upgrade))return;setPowers(upgradePower(loadPowerState(),r.id))}
function equip(id:PowerId){setPowers(toggleEquipPower(loadPowerState(),id))}
return <main className="building-hub" style={{backgroundImage:`url(${forgeBg})`}}><header className="building-hub__top"><div><div className="building-hub__eyebrow">KUŹNIA KART I MOCY · LV {forge}</div><h1 className="building-hub__title">Tworzenie kart bojowych</h1></div><button className="building-hub__back" onClick={onBack}>← WRÓĆ DO HUBU</button></header><section className="building-hub__content"><div className="building-resourcebar"><span>⚡ {progress.memeEnergy}</span><span>💎 {progress.relics}</span><span>🐻 {progress.bearFragments}</span><span>🃏 {progress.cardFragments}</span><span>📜 {progress.comicFragments}</span><span>✦ {progress.intel}</span></div><div className="building-hub__hero"><h2>Aktywne moce: {powers.equipped.length}/3</h2><p>Kartę najpierw tworzysz z materiałów zdobywanych na mapie, w misjach, Arenie, ruinach, kopalniach i po bossach. Potem wyposażasz maksymalnie 3 karty do walki.</p></div><div className="building-hub__grid">{RECIPES.map(r=>{const unlocked=forge>=r.level;const owned=hasPower(powers,r.id);const power=powers.crafted.find(x=>x.id===r.id);const equipped=powers.equipped.includes(r.id);return <article className={`building-card ${unlocked?'ready':'locked'} ${equipped?'selected':''}`} key={r.id}><div className="building-card__icon">{r.icon}</div><h3>{r.name}</h3><p>{r.desc}</p><div className="building-cost"><strong>DO STWORZENIA:</strong> {formatCost(r.cost)}</div><div className="building-card__meta"><span className="building-chip">Kuźnia LV {r.level}</span>{power&&<span className="building-chip">Moc LV {power.level}</span>}{power&&<span className="building-chip">Ładunki {power.charges}</span>}</div>{!owned?<button className="building-action" disabled={!unlocked||!canAfford(progress,r.cost)} onClick={()=>make(r)}>{!unlocked?'ZABLOKOWANE':canAfford(progress,r.cost)?'WYTWÓRZ KARTĘ':'BRAK MATERIAŁÓW'}</button>:<><button className={`building-action ${equipped?'green':''}`} onClick={()=>equip(r.id)}>{equipped?'✓ WYPOSAŻONA':'WYPOSAŻ DO WALKI'}</button><div className="building-cost"><strong>ULEPSZENIE:</strong> {formatCost(r.upgrade)}</div><button className="building-action secondary" disabled={!canAfford(progress,r.upgrade)} onClick={()=>levelUp(r)}>{canAfford(progress,r.upgrade)?'ULEPSZ MOC':'BRAK MATERIAŁÓW'}</button></>}</article>})}</div></section></main>}
