import { useMemo, useState } from "react";
import "./BuildingHubShared.css";
import archiveBg from "../../assets/game/comic_archive_hub_clean.png";
import pepeImg from "../../assets/game/char_polishpepe.png";
import bocianImg from "../../assets/game/char_bocian.png";
import bearImg from "../../assets/game/char_bear_scout.png";
import { useGameProgress } from "./Progress";
interface Props{currentChapter:number;chapter1Completed:boolean;quest1Completed:boolean;quest2Completed:boolean;intel:number;bearFragments:number;onBack:()=>void;}
type Tab='chapters'|'notes'|'people'|'enemies'|'places'|'secrets';type Entry={title:string;short:string;body:string;unlocked:boolean;image?:string};
function readMapSave(){try{return JSON.parse(localStorage.getItem('plpe-world-map-progress-v4')||localStorage.getItem('plpe-world-map-progress-v3')||'{}')}catch{return{}}}
export default function ComicArchiveHub({onBack}:Props){const {progress}=useGameProgress();const[tab,setTab]=useState<Tab>('chapters');const[open,setOpen]=useState<Entry|null>(null);const map=useMemo(readMapSave,[]);const visited:string[]=Array.isArray(map.visitedLocations)?map.visitedLocations:[];const discoveries:string[]=Array.isArray(map.discoveries)?map.discoveries:[];const notes:Entry[]=[{title:'Wojna budzi się',short:'Pierwsze ślady organizacji Bear Army.',body:'Po opuszczeniu Klasztoru PolishPepe odkrywa, że niedźwiedzie nie są przypadkowymi napastnikami. Ślady patroli, czerwone fragmenty materiału i posterunki wskazują na zorganizowaną armię.',unlocked:visited.includes('forest-pass')||progress.quest1Completed},{title:'Raport Zwiadowcy',short:'Informacje z pierwszych wypraw.',body:'Zwiad potwierdza ruch wojsk po wschodniej stronie przełęczy. Ciemna Dolina rozwija posterunki i próbuje utrzymywać połączenia pomiędzy obozami.',unlocked:progress.intel>=2},{title:'Fragment pamięci',short:'PolishPepe rozpoznaje symbol, którego nie powinien pamiętać.',body:'Znaleziony znak wywołuje u Pepe krótkie wspomnienie. Nie potrafi jeszcze ustalić, skąd go zna, ale Bocian wie więcej, niż mówi.',unlocked:progress.comicFragments>0||discoveries.length>2},{title:'Wróg odpowiada',short:'Ciemna Dolina zaczyna reagować na działania bohaterów.',body:'Po pierwszych zwycięstwach Bear Army wzmacnia front. Posterunki zostają ufortyfikowane, a patrole zaczynają odbijać utracone miejsca.',unlocked:visited.includes('watchtower')||progress.bearFragments>=4},{title:'Rada Wojenna',short:'Plan obrony Klasztoru i budowy wież.',body:'Bocian proponuje zabezpieczanie odbitych punktów wieżami. Wieża z obsadą strażników może zatrzymać próbę odbicia terytorium przez Bear Army.',unlocked:visited.includes('old-bridge')||progress.chapter1Completed}];
const people:Entry[]=[{title:'PolishPepe',short:'Główny bohater.',body:'Wędrowiec, który trafia do Klasztoru Bociana i stopniowo odkrywa własną przeszłość. Rozwija się przez walkę, eksplorację, trening i wyposażenie.',unlocked:true,image:pepeImg},{title:'Bocian',short:'Mentor i mag wsparcia.',body:'Opiekun Klasztoru. W walce leczy, zamraża, usypia, wzmacnia i może atakować magią. Jego ranga rozwija możliwości wsparcia.',unlocked:true,image:bocianImg}];
const enemies:Entry[]=[{title:'Bear Scout',short:'Zwiadowca Bear Army.',body:'Lekki przeciwnik. Szybki, ale słabiej opancerzony. Spotykany w pierwszych patrolach.',unlocked:progress.bearFragments>0,image:bearImg},{title:'Bear Elite',short:'Ciężki strażnik.',body:'Wysoka obrona i silne uderzenia. Wymaga bloków, kontroli Bociana i lepszego ekwipunku.',unlocked:progress.bearFragments>=3,image:bearImg},{title:'Bear Commander',short:'Dowódca oddziału.',body:'Wzmacnia presję przeciwnika i jest jednym z głównych celów treningów Areny.',unlocked:progress.bearFragments>=6,image:bearImg},{title:'Wąż Jeziora Mgły',short:'Dziki przeciwnik wodny.',body:'Nie zajmuje terytorium. Broni swojego legowiska i może nakładać truciznę.',unlocked:visited.includes('mist-lake')}];
const places:Entry[]=['monastery','forest-pass','mist-lake','old-bridge','watchtower','bear-camp'].map(id=>({title:id.replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase()),short:visited.includes(id)?'Odwiedzone miejsce.':'Jeszcze nieodkryte.',body:visited.includes(id)?`Zapis podróży potwierdza wizytę w lokacji ${id}. Szczegółowe wpisy będą rozbudowywane wraz ze scenariuszem i kolejnymi wydarzeniami.`:'Brak danych. Najpierw odkryj to miejsce na mapie.',unlocked:visited.includes(id)}));
let entries:Entry[]=[];if(tab==='notes')entries=notes;if(tab==='people')entries=people;if(tab==='enemies')entries=enemies;if(tab==='places')entries=places;if(tab==='secrets')entries=[{title:'Pierwszy sygnał',short:'Ślad przy Klasztorze.',body:'Pierwszy sygnał rozpoczyna właściwą ścieżkę przygody i prowadzi Pepe poza bezpieczny teren.',unlocked:progress.quest1Completed},{title:'Ciemna Dolina',short:'Źródło wschodniego zagrożenia.',body:'Pełny raport wymaga większej ilości Intel i postępu na mapie.',unlocked:progress.intel>=3}];
return <main className="building-hub" style={{backgroundImage:`url(${archiveBg})`}}><header className="building-hub__top"><div><div className="building-hub__eyebrow">ARCHIWUM KOMIKSU</div><h1 className="building-hub__title">Wiedza, historia i zapiski</h1></div><button className="building-hub__back" onClick={onBack}>← WRÓĆ DO HUBU</button></header><section className="building-hub__content"><div className="building-resourcebar"><span>✦ {progress.intel} Intel</span><span>📜 {progress.comicFragments} Comic</span><span>🐻 {progress.bearFragments} Bear</span><span>📖 Chapter {progress.chapter}</span></div><div className="building-tabs">{([['chapters','ROZDZIAŁY'],['notes','ZAPISKI'],['people','POSTACIE'],['enemies','PRZECIWNICY'],['places','MIEJSCA'],['secrets','SEKRETY']] as [Tab,string][]).map(([k,l])=><button className={`building-tab ${tab===k?'active':''}`} key={k} onClick={()=>setTab(k)}>{l}</button>)}</div>{tab==='chapters'?<div className="building-hub__grid">{[1,2,3,4,5,6].map(ch=>{const unlocked=ch===1||(progress.chapter1Completed&&ch<=progress.chapter);return <article className={`building-card ${unlocked?'ready':'locked'}`} key={ch}><div className="building-card__icon">📖</div><h3>Rozdział {ch}</h3><p>{ch===1?'Przebudzenie, Klasztor i pierwsze ślady Bear Army.':'Treść odsłania się wraz z fabułą.'}</p><button className="building-action secondary" disabled={!unlocked} onClick={()=>unlocked&&setOpen({title:`Rozdział ${ch}`,short:'Kronika rozdziału',body:ch===1?'PolishPepe dociera do Klasztoru Bociana. Pierwsze sygnały zagrożenia prowadzą go na Leśną Przełęcz, gdzie zaczyna się właściwa eksploracja i konflikt z Bear Army.':'Ten rozdział zostanie uzupełniony przez dalszy scenariusz.',unlocked})}>CZYTAJ</button></article>})}</div>:<div className="building-hub__grid">{entries.map(e=><article className={`building-card ${e.unlocked?'ready':'locked'}`} key={e.title}>{e.image&&<div className="building-card__portrait"><img src={e.image} alt={e.title}/></div>}<h3>{e.unlocked?e.title:'???'}</h3><p>{e.unlocked?e.short:'Wpis jeszcze nie został odkryty.'}</p><button className="building-action secondary" disabled={!e.unlocked} onClick={()=>setOpen(e)}>OTWÓRZ WPIS</button></article>)}</div>}</section>{open&&<div className="codex-modal" onClick={()=>setOpen(null)}><article className="codex-modal__card" onClick={e=>e.stopPropagation()}><button className="building-hub__back codex-modal__close" onClick={()=>setOpen(null)}>✕</button>{open.image&&<div className="building-card__portrait"><img src={open.image} alt={open.title}/></div>}<h2>{open.title}</h2><p>{open.body}</p></article></div>}</main>}
